 import {
  FinanceRequestRow,
  FinanceRequestDetail,
  FinanceDashboardSummary,
  FinanceHoldRow,
  FinanceDebtRow,
  FinanceRestrictionRow,
  FinanceAuditRow,
  FinanceWalletExposure,
  FinanceAccountSnapshot,
} from "./types";

const exposureCustomerSyp: FinanceWalletExposure = {
  accountId: "acc_101",
  accountClass: "CUSTOMER",
  balances: [
    {
      currency: "SYP",
      available: 2000000,
      held: 0,
      frozen: 0,
      pendingIn: 0,
      pendingOut: 1500000,
    },
    {
      currency: "USD",
      available: 0,
      held: 0,
      frozen: 0,
      pendingIn: 0,
      pendingOut: 0,
    },
  ],
  openDebtCount: 0,
  overdueDebtCount: 0,
  activeHoldCount: 0,
  activeRestrictionCount: 0,
};

const exposureMerchantGov: FinanceWalletExposure = {
  accountId: "acc_102",
  accountClass: "MERCHANT",
  balances: [
    {
      currency: "SYP",
      available: 51000000,
      held: 0,
      frozen: 0,
      pendingIn: 0,
      pendingOut: 50000000,
    },
    {
      currency: "USD",
      available: 1500,
      held: 0,
      frozen: 0,
      pendingIn: 0,
      pendingOut: 0,
    },
  ],
  openDebtCount: 0,
  overdueDebtCount: 0,
  activeHoldCount: 0,
  activeRestrictionCount: 0,
};

const exposureDriver: FinanceWalletExposure = {
  accountId: "acc_103",
  accountClass: "DRIVER",
  balances: [
    {
      currency: "SYP",
      available: 50000,
      held: 0,
      frozen: 0,
      pendingIn: 200000,
      pendingOut: 0,
    },
    {
      currency: "USD",
      available: 0,
      held: 0,
      frozen: 0,
      pendingIn: 0,
      pendingOut: 0,
    },
  ],
  openDebtCount: 0,
  overdueDebtCount: 0,
  activeHoldCount: 0,
  activeRestrictionCount: 0,
};

const exposureMerchantDebt: FinanceWalletExposure = {
  accountId: "acc_104",
  accountClass: "MERCHANT",
  balances: [
    {
      currency: "SYP",
      available: 8000000,
      held: 2000000,
      frozen: 500000,
      pendingIn: 0,
      pendingOut: 5000000,
    },
    {
      currency: "USD",
      available: 250,
      held: 0,
      frozen: 0,
      pendingIn: 0,
      pendingOut: 0,
    },
  ],
  openDebtCount: 1,
  overdueDebtCount: 1,
  activeHoldCount: 1,
  activeRestrictionCount: 1,
};

export const mockSummary: FinanceDashboardSummary = {
  pendingFirstReview: 12,
  awaitingFinalApproval: 4,
  processingRequests: 3,
  failedRequestsToday: 1,
  frozenAccounts: 2,
  totalHeldFunds: 45000000,
  auctionDepositsHeld: 32000000,
  outstandingDebts: 5500000,
  overdueDebts: 1200000,
  highRiskAccounts: 3,
};

export const mockRequestsRows: FinanceRequestRow[] = [
  {
    id: "req_001",
    type: "PAYOUT",
    accountClass: "CUSTOMER",
    accountType: "STANDARD_CUSTOMER_WALLET",
    accountId: "acc_101",
    accountName: "Ahmad Hassan",
    accountOwner: "Ahmad Hassan",
    amount: 1500000,
    currency: "SYP",
    availableBalance: 2000000,
    heldBalance: 0,
    frozenBalance: 0,
    walletExposure: exposureCustomerSyp,
    status: "UNDER_REVIEW",
    approvalStage: "AWAITING_FIRST_REVIEW",
    currentOwner: "Unassigned",
    riskFlags: [],
    linkedReference: null,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
    slaWaitingTime: "2 hours",
    badges: [],
  },
  {
    id: "req_002",
    type: "PAYOUT",
    accountClass: "MERCHANT",
    accountType: "GOVERNMENT_AUCTION_SETTLEMENT",
    accountId: "acc_102",
    accountName: "Metal Corp",
    accountOwner: "Omar Zidan",
    amount: 50000000,
    currency: "SYP",
    availableBalance: 51000000,
    heldBalance: 0,
    frozenBalance: 0,
    walletExposure: exposureMerchantGov,
    status: "UNDER_REVIEW",
    approvalStage: "AWAITING_FINAL_APPROVAL",
    currentOwner: "Final Approver Team",
    riskFlags: [
      {
        id: "flag_1",
        code: "HIGH_VALUE",
        description: "Payout exceeds high-value threshold",
        severity: "MEDIUM",
        appliedAt: "2026-03-20T08:00:00Z",
      },
    ],
    linkedReference: {
      id: "auc_55",
      type: "AUCTION",
      label: "Government Scrap Metal Auction",
    },
    createdAt: "2026-03-20T08:00:00Z",
    updatedAt: "2026-03-20T09:30:00Z",
    slaWaitingTime: "4 hours",
    badges: ["Final Approval Needed", "Government Waiver"],
  },
  {
    id: "req_003",
    type: "DEPOSIT",
    accountClass: "DRIVER",
    accountType: "DRIVER_SETTLEMENT_WALLET",
    accountId: "acc_103",
    accountName: "Sami Logistics",
    accountOwner: "Sami Al-Masri",
    amount: 200000,
    currency: "SYP",
    availableBalance: 50000,
    heldBalance: 0,
    frozenBalance: 0,
    walletExposure: exposureDriver,
    status: "FAILED",
    approvalStage: "NONE",
    currentOwner: "System",
    riskFlags: [],
    linkedReference: null,
    createdAt: "2026-03-20T07:15:00Z",
    updatedAt: "2026-03-20T07:20:00Z",
    slaWaitingTime: "Failed",
    badges: ["Failed"],
  },
  {
    id: "req_004",
    type: "PAYOUT",
    accountClass: "MERCHANT",
    accountType: "MERCHANT_PRIMARY_WALLET",
    accountId: "acc_104",
    accountName: "Scrap Traders Ltd",
    accountOwner: "Khaled Z",
    amount: 5000000,
    currency: "SYP",
    availableBalance: 8000000,
    heldBalance: 2000000,
    frozenBalance: 500000,
    walletExposure: exposureMerchantDebt,
    status: "UNDER_REVIEW",
    approvalStage: "AWAITING_FIRST_REVIEW",
    currentOwner: "Reviewer Team",
    riskFlags: [
      {
        id: "flag_2",
        code: "DEBT_OPEN",
        description: "Account has open commission debt",
        severity: "HIGH",
        appliedAt: "2026-03-19T00:00:00Z",
      },
    ],
    linkedReference: null,
    createdAt: "2026-03-20T11:00:00Z",
    updatedAt: "2026-03-20T11:00:00Z",
    slaWaitingTime: "1 hour",
    badges: ["Debt Open", "High Risk", "Frozen Balance"],
  },
];

export const mockHolds: FinanceHoldRow[] = [
  {
    id: "hold_1",
    holdType: "AUCTION_DEPOSIT",
    accountId: "acc_104",
    accountName: "Scrap Traders Ltd",
    accountClass: "MERCHANT",
    accountType: "MERCHANT_PRIMARY_WALLET",
    amount: 2000000,
    currency: "SYP",
    status: "OPEN",
    referenceType: "AUCTION",
    referenceId: "auc_100",
    createdAt: "2026-03-15T00:00:00Z",
    expiresAt: "2026-04-15T00:00:00Z",
  },
];

export const mockDebts: FinanceDebtRow[] = [
  {
    id: "debt_1",
    accountId: "acc_104",
    accountName: "Scrap Traders Ltd",
    accountClass: "MERCHANT",
    accountType: "MERCHANT_PRIMARY_WALLET",
    debtType: "COMMISSION",
    amount: 500000,
    currency: "SYP",
    outstanding: 500000,
    dueDate: "2026-03-01T00:00:00Z",
    agingBucket: "8-30_DAYS",
    status: "OVERDUE",
    waiverApplied: false,
    lastActionAt: null,
  },
];

export const mockRestrictions: FinanceRestrictionRow[] = [
  {
    accountId: "acc_999",
    accountName: "Suspicious Trader",
    accountClass: "MERCHANT",
    accountType: "MERCHANT_PRIMARY_WALLET",
    restrictionType: "FROZEN_DEBIT",
    status: "ACTIVE",
    reason: "Suspicious payout pattern",
    appliedBy: "Risk Manager",
    appliedAt: "2026-03-18T12:00:00Z",
    frozenBalance: 3500000,
    currency: "SYP",
    relatedFlags: [
      {
        id: "flag_3",
        code: "VELOCITY_SPIKE",
        description: "3 payouts above threshold within 1 hour",
        severity: "CRITICAL",
        appliedAt: "2026-03-18T11:45:00Z",
      },
    ],
  },
];

export const mockAuditLogs: FinanceAuditRow[] = [
  {
    id: "adt_1",
    actor: "Admin User",
    action: "APPROVE_FIRST_STAGE",
    reason: "Documents verified",
    ipAddress: "192.168.1.1",
    timestamp: "2026-03-20T09:30:00Z",
    entityType: "REQUEST",
    entityId: "req_002",
  },
];

const snapshotAcc102: FinanceAccountSnapshot = {
  accountId: "acc_102",
  accountClass: "MERCHANT",
  accountType: "GOVERNMENT_AUCTION_SETTLEMENT",
  ownerName: "Omar Zidan",
  balances: exposureMerchantGov.balances,
  debtStatus: "CLEAR",
  restrictionStatus: "NONE",
  restrictionTypes: [],
  riskScore: 25,
  riskFlags: mockRequestsRows[1].riskFlags,
  frozenBalanceTotal: 0,
  heldBalanceTotal: 0,
  availableBalanceTotal: 51001500,
  pendingInTotal: 0,
  pendingOutTotal: 50000000,
  lastActivityAt: "2026-03-19T00:00:00Z",
};

export const mockRequestDetail: FinanceRequestDetail = {
  ...mockRequestsRows[1],
  snapshot: snapshotAcc102,
  approvalChain: [
    {
      role: "MAKER",
      actorId: "admin_1",
      actorName: "Ahmad",
      timestamp: "2026-03-20T09:30:00Z",
      note: "Approved first review, forwarding to final approver",
      status: "APPROVED",
    },
    {
      role: "FINAL_APPROVER",
      actorId: null,
      actorName: null,
      timestamp: null,
      note: null,
      status: "PENDING",
    },
  ],
  timeline: [
    {
      id: "t_1",
      timestamp: "2026-03-20T08:00:00Z",
      type: "CREATED",
      actor: "System",
    },
    {
      id: "t_2",
      timestamp: "2026-03-20T09:30:00Z",
      type: "FIRST_REVIEW",
      actor: "Ahmad",
      note: "Approved first review",
    },
  ],
  holds: [],
  debts: [],
  restrictions: [],
  auditTrail: mockAuditLogs,
};